// Writes src/core/defaults.ts from config/router.json and config/calibration.json.
// Claude Code's module loader does not import .json, and the router
// (hooks/register.ts) must have its defaults even without reading files: the JSON
// stays the source of truth, the .ts is a generated copy of it.
//
// Usage: node scripts/generate-defaults.ts          rewrites the file
//        node scripts/generate-defaults.ts --check  exit 1 if the file does not match (CI)
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
export const TARGET = join(root, 'src', 'core', 'defaults.ts')

export function generateDefaults(router: string, calibration: string): string {
  const r = JSON.parse(router)
  const c = JSON.parse(calibration)
  return [
    '// GENERATED by scripts/generate-defaults.ts from config/router.json and',
    '// config/calibration.json: do not edit by hand. Change the JSON and run',
    '// `node scripts/generate-defaults.ts` again; CI checks that there is no drift.',
    '',
    `export const DEFAULT_ROUTER = ${JSON.stringify(r, null, 2)} as const`,
    '',
    `export const DEFAULT_CALIBRATION = ${JSON.stringify(c, null, 2)} as const`,
    '',
  ].join('\n')
}

export function expectedDefaults(): string {
  return generateDefaults(
    readFileSync(join(root, 'config', 'router.json'), 'utf8'),
    readFileSync(join(root, 'config', 'calibration.json'), 'utf8'),
  )
}

function main(argv: string[]): number {
  const text = expectedDefaults()
  if (argv.includes('--check')) {
    let current = ''
    try {
      current = readFileSync(TARGET, 'utf8')
    } catch {
      current = ''
    }
    if (current !== text) {
      console.error('src/core/defaults.ts does not match config/router.json and config/calibration.json: run node scripts/generate-defaults.ts again')
      return 1
    }
    console.log('ok src/core/defaults.ts')
    return 0
  }
  writeFileSync(TARGET, text)
  console.log('wrote src/core/defaults.ts')
  return 0
}

// Run as a program, not imported (by the structure test).
if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  process.exitCode = main(process.argv.slice(2))
}
